### ISSUE TITLE
Choose a style guide and follow it properly through out the project

### ISSUE THREAD

**Issue by sravan-s** [RijoKJose/FoodTestApplication#4]
Inconsistent indentation of assignment operators(=) https://github.com/RijoKJose/FoodTestApplication/blob/master/app/src/main/java/com/projects/myapp/foodtestapplication/MainActivity.java

 You can follow this guide (or something similar) https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md#224-use-spaces-for-indentation

The important idea is to be consistent.

**Comment by RijoKJose** [comment]
Ok.Actually it is a test project .
