### ISSUE TITLE
The items inside each if and else if can be generalized

### ISSUE THREAD

**Issue by sravan-s** [RijoKJose/FoodTestApplication#6]
@RijoKJose 

https://github.com/RijoKJose/FoodTestApplication/blob/master/app/src/main/java/com/projects/myapp/foodtestapplication/MainActivity.java

eg:
function setData(foodImg, foodName, ... , foodRate) {
    foodimageView.setBackgroundResource(foodImg);
    fodName.setText(foodName);
    ....
    rate.setText(foodRate);
}

if( pos = 1) {
  setData(R.drawable.burger, "burger", ...);
} else if( pos = 2) {
  setData(R.drawable.egg, "egg",  ...);
}

Also, possibly you can get the arguments from a data structure, mapping the variable 'pos'.

**Comment by RijoKJose** [comment]
Ok
